### ISSUE TITLE
有在生产上使用吗？

### ISSUE THREAD

**Issue by pandalin** [beston123/Tarzan#1]

**Comment by beston123** [comment]
功能还在开发中，近期会上生产环境试用

**Comment by pandalin** [comment]
感觉完善后可以替代阿里的ONS

**Comment by Xiaobaxi** [comment]
依赖库dianping的cat跟baymax-spring下载不到

**Comment by beston123** [comment]
@Xiaobaxi 两个依赖项目地址
dianping的cat：https://github.com/dianping/cat
baymax：https://github.com/tongbanjie/baymax
